"use client";
import { useEffect, useRef, useState } from "react";
import { Heart, MessageCircle, Share2, Bookmark, MoreVertical, Play, Volume2, VolumeX, Music, Pause } from "lucide-react";
import { cn } from "@/app/lib/utils";
import CommentSheet from "./Comment";
import { useLanguage } from "@/app/context/LanguageContext";

interface Video { id: string; videoUrl: string; thumbnailUrl: string; user: { name: string; username: string; avatar?: string }; description: string; music: string; likes: number; comments: number; shares: number; isFollowing?: boolean; }
export default function VideoCard({ video, isActive }: { video: Video; isActive: boolean }) {
  const videoRef = useRef<HTMLVideoElement>(null); const [isPlaying, setIsPlaying] = useState(false); const [isMuted, setIsMuted] = useState(true); const [isLiked, setIsLiked] = useState(false); const [isSaved, setIsSaved] = useState(false); const [likes, setLikes] = useState(video.likes); const [showHeart, setShowHeart] = useState(false); const [isFollowing, setIsFollowing] = useState(video.isFollowing || false); const [showComments, setShowComments] = useState(false); const { t } = useLanguage();
  useEffect(() => { const el = videoRef.current; if (!el) return; if (isActive) { el.play().then(() => setIsPlaying(true)).catch(() => setIsPlaying(false)); } else { el.pause(); setIsPlaying(false); } }, [isActive]);
  const togglePlay = () => { const el = videoRef.current; if (!el) return; if (el.paused) { el.play().then(() => setIsPlaying(true)).catch(() => undefined); } else { el.pause(); setIsPlaying(false); } };
  const like = () => { setIsLiked((liked) => { setLikes((count) => count + (liked ? -1 : 1)); return !liked; }); setShowHeart(true); window.setTimeout(() => setShowHeart(false), 800); };
  const handleDoubleTap = (e: React.MouseEvent) => { e.preventDefault(); if (!isLiked) like(); else { setShowHeart(true); window.setTimeout(() => setShowHeart(false), 800); } };
  const formatNumber = (num: number) => num >= 1000000 ? `${(num / 1000000).toFixed(1)}M` : num >= 1000 ? `${(num / 1000).toFixed(1)}K` : String(num);
  return <article className="relative flex h-full w-full items-center justify-center bg-background px-0 md:px-6"><div className="relative h-full w-full max-w-2xl overflow-hidden bg-card md:my-4 md:h-[calc(100%-2rem)] md:rounded-3xl md:border md:border-border/70 md:shadow-2xl" onClick={togglePlay} onDoubleClick={handleDoubleTap}>
    <video ref={videoRef} src={video.videoUrl} poster={video.thumbnailUrl} loop muted={isMuted} playsInline preload={isActive ? "auto" : "metadata"} className="size-full object-cover" aria-label={`Video by ${video.user.username}`} />
    <div className="pointer-events-none absolute inset-0 bg-gradient-to-t from-background via-transparent to-background/30 opacity-90" />
    {!isPlaying && <div className="pointer-events-none absolute inset-0 flex items-center justify-center"><span className="flex size-16 items-center justify-center rounded-full bg-background/40 backdrop-blur-md"><Play className="ml-1 size-7 fill-current" /></span></div>}
    {showHeart && <div className="pointer-events-none absolute inset-0 flex items-center justify-center"><Heart className="size-32 animate-heart-burst text-accent" fill="currentColor" /></div>}
    <div className="absolute right-4 top-4 flex gap-2"><button aria-label={isMuted ? "Unmute video" : "Mute video"} onClick={(e) => { e.stopPropagation(); const next = !isMuted; setIsMuted(next); if (videoRef.current) videoRef.current.muted = next; }} className="rounded-full bg-background/45 p-3 backdrop-blur-md hover:bg-background/70">{isMuted ? <VolumeX className="size-4" /> : <Volume2 className="size-4" />}</button></div>
    <div className="absolute bottom-6 left-5 right-20 animate-slide-up md:bottom-8 md:left-7"><div className="mb-4 flex items-center gap-3"><div className="gradient-bg flex size-11 items-center justify-center rounded-full p-0.5"><div className="flex size-full items-center justify-center rounded-full bg-card text-sm font-bold">{video.user.name.slice(0,1).toUpperCase()}</div></div><div className="min-w-0"><div className="flex items-center gap-2"><h2 className="truncate font-bold">@{video.user.username}</h2><button onClick={(e) => { e.stopPropagation(); setIsFollowing(!isFollowing); }} className={cn("rounded-full px-3 py-1 text-xs font-bold", isFollowing ? "bg-muted text-muted-foreground" : "bg-primary text-primary-foreground")}>{isFollowing ? t("followed") || "Following" : t("follow") || "Follow"}</button></div><p className="truncate text-xs text-muted-foreground">{video.user.name}</p></div></div><p className="mb-3 line-clamp-2 text-sm leading-relaxed">{video.description}</p><div className="flex items-center gap-2 text-xs text-muted-foreground"><Music className="size-4 text-secondary" /><span className="truncate">{video.music || "Original sound"}</span></div></div>
    <div className="absolute bottom-24 right-3 flex flex-col items-center gap-4 md:bottom-28 md:right-5"><button aria-label="Like video" onClick={(e) => { e.stopPropagation(); like(); }} className="flex flex-col items-center gap-1 text-xs"><span className={cn("flex size-11 items-center justify-center rounded-full backdrop-blur-md", isLiked ? "bg-accent/20 text-accent" : "bg-background/45")}><Heart className="size-6" fill={isLiked ? "currentColor" : "none"} /></span>{formatNumber(likes)}</button><button aria-label="View comments" onClick={(e) => { e.stopPropagation(); setShowComments(true); }} className="flex flex-col items-center gap-1 text-xs"><span className="flex size-11 items-center justify-center rounded-full bg-background/45 backdrop-blur-md"><MessageCircle className="size-6" /></span>{formatNumber(video.comments)}</button><button aria-label="Share video" onClick={(e) => e.stopPropagation()} className="flex size-11 items-center justify-center rounded-full bg-background/45 backdrop-blur-md"><Share2 className="size-6" /></button><button aria-label="Save video" onClick={(e) => { e.stopPropagation(); setIsSaved(!isSaved); }} className={cn("flex size-11 items-center justify-center rounded-full backdrop-blur-md", isSaved ? "bg-secondary/20 text-secondary" : "bg-background/45")}><Bookmark className="size-6" fill={isSaved ? "currentColor" : "none"} /></button><button aria-label="More options" onClick={(e) => e.stopPropagation()} className="flex size-11 items-center justify-center rounded-full bg-background/45 backdrop-blur-md"><MoreVertical className="size-5" /></button><div className="flex size-10 items-center justify-center rounded-full border-2 border-border bg-primary/20"><Pause className="size-4" /></div></div>
  </div><CommentSheet isOpen={showComments} onClose={() => setShowComments(false)} videoId={video.id} /></article>;
}
