"use client";
import { useEffect, useRef, useState } from "react";
import VideoCard from "./VideoCard";

type FeedVideo = { id: string; videoUrl: string; thumbnailUrl: string; user: { name: string; username: string; avatar?: string }; description: string; music: string; likes: number; comments: number; shares: number; isFollowing?: boolean; };
function toAbsoluteUrl(url: string) { if (!url || /^https?:\/\//.test(url) || !url.startsWith("/")) return url; const endpoint = process.env.NEXT_PUBLIC_URL_ENDPOINT; if (!endpoint) return url; const base = (endpoint.startsWith("http") ? endpoint : `https://${endpoint}`).replace(/\/$/, ""); return `${base}${url}`; }
export default function VideoFeed() {
  const [activeVideoIndex, setActiveVideoIndex] = useState(0); const [videos, setVideos] = useState<FeedVideo[]>([]); const containerRef = useRef<HTMLDivElement>(null);
  useEffect(() => { let cancelled = false; fetch("/api/videos", { cache: "no-store" }).then(async (res) => { if (!res.ok) return; const data = await res.json(); const mapped = Array.isArray(data) ? data.map((v: any) => ({ id: String(v._id ?? v.id), videoUrl: toAbsoluteUrl(v.videoUrl), thumbnailUrl: toAbsoluteUrl(v.thumbnailUrl), user: { name: v.user?.name || "User", username: v.user?.username || "user", avatar: v.user?.avatar }, description: v.description || "", music: v.music || "", likes: Number(v.likes || 0), comments: Number(v.comments || 0), shares: Number(v.shares || 0) })) : []; if (!cancelled) setVideos(mapped); }).catch(() => { if (!cancelled) setVideos([]); }); return () => { cancelled = true; }; }, []);
  useEffect(() => { const container = containerRef.current; if (!container) return; const items = Array.from(container.querySelectorAll<HTMLElement>("[data-feed-item]")); const observer = new IntersectionObserver((entries) => { const visible = entries.filter((entry) => entry.isIntersecting).sort((a,b) => b.intersectionRatio - a.intersectionRatio)[0]; if (visible) setActiveVideoIndex(Number(visible.target.getAttribute("data-index"))); }, { root: container, threshold: [0.6, 0.85] }); items.forEach((item) => observer.observe(item)); return () => observer.disconnect(); }, [videos.length]);
  return <div ref={containerRef} className="h-[calc(100vh-4rem)] snap-y snap-mandatory overflow-y-scroll scrollbar-hide">{videos.map((video, index) => <div key={video.id} data-feed-item data-index={index} className="h-full snap-start snap-always"><VideoCard video={video} isActive={index === activeVideoIndex} /></div>)}{!videos.length && <div className="flex h-full items-center justify-center p-6"><div className="glass max-w-sm rounded-3xl p-8 text-center"><div className="gradient-bg mx-auto mb-5 flex size-14 items-center justify-center rounded-2xl text-xl font-black text-primary-foreground">RN</div><h1 className="mb-2 text-xl font-bold">Your feed is quiet</h1><p className="text-sm leading-relaxed text-muted-foreground">Follow creators or upload your first reel to bring this space to life.</p></div></div>}</div>;
}
